# Generated by Django 3.1.4 on 2020-12-14 18:48

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('product_path', models.FileField(upload_to=project.models.upload_location_product, verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название версии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.product', verbose_name='Версия продукта')),
            ],
            options={
                'verbose_name': 'Изменение',
                'verbose_name_plural': 'Изменения',
            },
        ),
    ]
